services:
  db:
    env_file:
      - .env.prod

  migration:
    env_file:
      - .env.prod

  redis:
    env_file:
      - .env.prod

  web:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.prod

  worker:
    command: celery -A app.celery_app.celery worker -l info --concurrency=1
    env_file:
      - .env.prod

  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: nginx_proxy
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
