services:
  web:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    command: celery -A app.celery_app.celery worker -l info --concurrency=1

  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: nginx_proxy
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh
