"""add composed_image_id to service

Revision ID: 750b12fb0712
Revises: a4667a7f3e7c
Create Date: 2025-08-15 02:58:41.386263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750b12fb0712'
down_revision: Union[str, Sequence[str], None] = 'a4667a7f3e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('composed_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'images', ['composed_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'composed_image_id')
    # ### end Alembic commands ###
