"""add area_image_id to Area

Revision ID: a4667a7f3e7c
Revises: f6a9623e3927
Create Date: 2025-08-05 23:56:09.839763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4667a7f3e7c'
down_revision: Union[str, Sequence[str], None] = 'f6a9623e3927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('area_image_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'areas', 'images', ['area_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'area_image_id')
    # ### end Alembic commands ###
