name: Deploy to S3 and to ec2

on:
  push:
    branches: ["prod"]

permissions:
  id-token: write # OIDC
  contents: read

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make artifact (zip)
        run: |
          mkdir -p dist
          # 배포에 필요한 파일만 압축: docker-compose들, app 코드, deploy/nginx.conf, etc.
          zip -r dist/app.zip \
            app docker-compose.yml docker-compose.prod.yml \
            deploy pyproject.toml poetry.lock \
            Dockerfile alembic alembic.ini font README.md \
            --exclude "**/__pycache__/**" ".git/**" ".github/**"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          TS=$(date +%Y%m%d-%H%M%S)
          aws s3 cp dist/app.zip s3://${{ secrets.S3_BUCKET_NAME }}/app-$TS.zip
          # 최신심볼릭 역할: latest.zip 덮어쓰기
          aws s3 cp dist/app.zip s3://${{ secrets.S3_BUCKET_NAME }}/latest.zip

  run_on_ec2:
    needs: build_and_upload
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          aws-region: ap-northeast-2

      - name: Put .env.docker into SSM Parameter Store
        env:
          ENV_DOCKER: ${{ secrets.ENV_DOCKER }}
        run: |
          aws ssm put-parameter \
            --name "/fastapi/env_docker" \
            --type "SecureString" \
            --value "$ENV_DOCKER" \
            --overwrite

      - name: Trigger SSM RunCommand on EC2
        run: |
          INSTANCE_ID="${{ secrets.EC2_INSTANCE_ID }}"
          S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy fastapi via S3 artifact" \
            --parameters '{
              "commands": [
                "set -e",
                "mkdir -p /opt/fastapi-app /opt/fastapi-app_tmp",
                "cd /opt/fastapi-app",
                "aws s3 cp s3://'"$S3_BUCKET_NAME"'/latest.zip /tmp/app.zip",
                "rm -rf /opt/fastapi-app_tmp/*",
                "unzip -o /tmp/app.zip -d /opt/fastapi-app_tmp",
                "command -v rsync >/dev/null 2>&1 || sudo yum install -y rsync || true",
                "if command -v rsync >/dev/null 2>&1; then rsync -a --delete /opt/fastapi-app_tmp/ /opt/fastapi-app/; else cp -a /opt/fastapi-app_tmp/. /opt/fastapi-app/; fi",
                "rm -f /tmp/app.zip",
                "aws ssm get-parameter --name /fastapi/env_docker --with-decryption --query Parameter.Value --output text > .env.docker",
                "docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.docker pull || true",
                "docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.docker build",
                "docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.docker up -d db redis",
                "docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.docker run --rm migration",
                "docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.docker up -d web worker reverse-proxy",
                "docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.docker ps",
                "docker image prune -f || true"
              ]
            }'
